name: CI

on:
  push:
    branches: [main, develop] # Adjust branches as needed
  pull_request:
    branches: [main, develop]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm' # Cache npm dependencies

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: npm ci # Use ci for faster, reliable installs in CI

      - name: Lint codebase
        run: npm run lint

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Add CODECOV_TOKEN to repo secrets
          # Optional: Specify flags, fail threshold, etc.
          # flags: unittests
          # fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build project
        run: npm run build

      # Optional: Archive build artifacts if needed for other jobs/debugging
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dist
      #     path: dist/
